version: '3'
#COMMENTS Above version shuold be written if your Docker version is not the newest.

services:
  web:
    image: nginx
    volumes:
    - ./dist/frontend:/usr/share/nginx/html
#COMMENTS ./dist/frontend above is the path to your html file.
    ports:
    - "8080:80"